services:
    apache-php:
        container_name: apache-php
        volumes:
            - /var/www/htdocs:/var/www/htdocs
        environment:
            - PHP_LIMIT_MEMORY=256M
            - TZ=Europe/Madrid
        ports:
            - 80:80
        image: apache-php
        user: "${UID}:${GID}"
